project:
  type: website
  output-dir: docs
  
website:
  title: "Semi-automated library generation from FTMS LC-MSn data"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Centroiding
        href: centroiding.qmd
      - text: Preprocessing
        href: ftms_preprocessing.qmd
      - text: Spectral Tree Selection
        href: ftms_filtering.qmd
      - text: Pseudo-MS/MS
        href: ftms_assembled.qmd
      - text: SQL database
        href: ftmsneg_flax_sql.qmd
theme: cosmo 