GeneralizeConXCMS<-function(XCMS){
	CON<-XCMS[,dim(XCMS)[2]]
	tim<-length(CON)-1
	CON.new<-c(1,rep(NA,tim))
	a=1
	i=2
	while(i<=length(CON)){
	 if(CON[i]==1){
	  CON.new[i]<-1
	 }else{
	  if(CON[i]==CON[i-1]){
	   CON.new[i]<-a
	  }else{
	   if(CON[i]>CON[i-1]){
	    a=a+1
	    CON.new[i]<-a
	   }
	  }
	 }
	 i=i+1
	}
	return(CON.new)
}
