LimKeys<-function(LCal.lst){
	Reg<-LCal.lst[[2]]
	Ind<-as.integer(LCal.lst[[1]][,1])
	RT<-as.numeric(LCal.lst[[1]][,2])
	Key3<-as.numeric(LCal.lst[[1]][,3])
	Key4<-as.numeric(LCal.lst[[1]][,4])
	Key5<-as.numeric(LCal.lst[[1]][,5])
	Key6<-as.numeric(LCal.lst[[1]][,6])
	Key7<-as.integer(LCal.lst[[1]][,7])
	RegRT<-as.numeric(rep(NA,length(RT)))
	i=1
	t1=0
	t2=0
	while(i<=length(RT)){
	 if(Reg[3]!=0){
	  t1=ifelse(RT[i]>Reg[3],RT[i]-Reg[3],0)
	 }
	 if(Reg[5]!=0){
	  t2=ifelse(RT[i]>Reg[5],RT[i]-Reg[5],0)
	 }
	 RegRT[i]<-Reg[1]+Reg[2]*RT[i]+Reg[4]*t1+Reg[6]*t2	 
	 i=i+1
	}
	Key<-data.frame(Ind,RT,Key3,Key4,Key5,Key6,Key7,RegRT)
	AveDiff<-mean(as.numeric(Key[,4])-as.numeric(Key[,8]))
	SDDiff<-sd(as.numeric(Key[,4])-as.numeric(Key[,8]))
	LowDiff<-AveDiff-1.96*SDDiff
	HighDiff<-AveDiff+1.96*SDDiff
	i=1
	while(i<=dim(Key)[1]){
	 if((as.numeric(Key[i,4])-as.numeric(Key[i,8])>=LowDiff)&
		(as.numeric(Key[i,4])-as.numeric(Key[i,8])<=HighDiff)){
	  i=i+1
	  next
	 }
	 Key<-Key[-i,]
	}
	row.names(Key)<-as.integer(seq(1,dim(Key)[1],1))
	Key<-Key[order(Key[,2]),]
	i=1
	while(i<dim(Key)[1]){
	 j=i+1
	 if((round(Key[i,2],2)==round(Key[j,2],2))&
		(round(Key[i,3],2)==round(Key[j,3],2))){
	  retDrift1<-abs(Key[i,4]-Key[i,8])
	  retDrift2<-abs(Key[j,4]-Key[j,8])
	  ifelse(retDrift1<=retDrift2,Key<-Key[-j,],Key<-Key[-i,])
	  next
	 }
	 i=i+1
	}
	Key<-Key[order(Key[,4]),]
	i=1
	while(i<dim(Key)[1]){
	 j=i+1
	 if((round(Key[i,4],2)==round(Key[j,4],2))&
		(round(Key[i,5],2)==round(Key[j,5],2))){
	  retDrift1<-abs(Key[i,4]-Key[i,8])
	  retDrift2<-abs(Key[j,4]-Key[j,8])
	  ifelse(retDrift1<=retDrift2,Key<-Key[-j,],Key<-Key[-i,])
	  next
	 }
	 i=i+1
	}
	Key<-Key[order(Key[,2]),]
	return(list(Key,Reg))
}